osx_image: xcode12.2
language: swift
xcode_workspace: QuizApp.xcworkspace
xcode_scheme: CI
xcode_sdk: iphonesimulator13.0
branches:
  only:
  - main
#script: xcodebuild clean build test ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO